config/routes.rb
Rails.application.routes.draw do
	
	resources :movies do 
		resources :comments
  	end
	
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		get 'logout' => :destroy
		delete 'logout' => :destroy
	end
	
 get 'discount' =>'movies#discount'
 get 'apply_discount' => 'movies#apply_discount'

 get 'pages/home'
 get 'pages/about'
 get 'search' => 'movies#search'
 
  resources :users
  resources :movies
  resources :genres

   root :to => "pages#home"
	

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:new, :create, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

   def search 
      @movies = Movie.search params[:query]
      unless @movies.empty?
        render 'index'
        else
          flash[:notice] = "no movie foind"
          @movie = Movie.all
          render 'index'
      end
    end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def discount
	  @genres = Genre.all
  end
  
  def apply_discount
	 
	  discount = params[:discount].to_f
	  @genre = Genre.find_by_id(params[:genre])
	  
	  @movies = @genre.movies
	  
	  @movies.each do |m|
		  m.apply_discount(m, discount)
		  m.save
	  end
	  render 'index', notice:  "Discount of 10% has successfully applied|"
 end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :poster, :trailer, :released_on, :rating, :genre_id, :price, :attachment)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
     <%= f.text_area :poster %> 
  </div>
  <div class="field">
    <%= f.label :trailer %><br>
    <%= f.text_area :trailer %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
</div>
  <div class="field">
    <%= f.label :released_on %><br>
    <%= f.date_select :released_on %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :rattach %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
	<%= text_field_tag(:query, params[:query]) %>
	<%= submit_tag "Search" %>
<% end %>

app/views/movies/discount.html.erb
<h4> Enter Discount rate here </h4>
<%= form_tag(apply_discount_path, method: :get) do %>
	<%= label_tag "Which Genre?" %>
	<%= select_tag "genre", options_from_collection_for_select(@genres, "id", "name") %>
</br>
</br>
	<%= label_tag "Discount Percentage" %>
	<%= text_field_tag "discount" %>  
</br>
	<% submit_tag 'Submit' %>
<% end %>

fild tag is the one used as a params.. in the controller. 

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<%= button_to 'Apply Discount', discount_path, method: :get %>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Poster</th>
      <th>Trailer</th>
      <th>Price</th>
      <th>Released on</th>
      <th>Rating</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %> 
      <tr>
        <td><%= movie.title %></td>
         <td><%= image_tag movie.poster, :size => '50x50' %></td>
        <td><%= movie.trailer %></td>
        <td><%= euro(movie.price) %></td>
        <td><%= movie.released_on %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.genre.name%></td>

        <td><%= link_to "Download File ", movie.attachment_url %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Poster:</strong>
  <%= image_tag @movie.poster, :size => '90x90' %>
</p>

<p>
  <strong>Trailer:</strong>
  <%= @movie.trailer %>
</p>

<p>
  <strong>Price:</strong>
  <%= euro @movie.price %>
</p>

<p>
  <strong>Released on:</strong>
  <%= @movie.released_on %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre.name %>
</p>

<h2>Star Rating and Comment: </h2>
	<%= form_for([@movie, Comment.new]) do |f| %>
	
	<h3><%= f.label :stars %>
	<% stars = [1, 2, 3, 4, 5] %>
	<% stars.each do |star| %>
		<%= f.radio_button :stars, star %><%= star%>
	<%end%>
	</h3></br>
	<%= f.text_area :content, :rows => 4, :cols => 40 %>
	<div class = "actions">
		<%= f.submit "Post a Commment" %>
	</div>
	<%end%>
	
	<% if @movie.comments.empty? %>
		<h3>You are the first Comment </h3>
	<%else%>
		<h2>What other felt about this </h2>
		<% @movie.comments.reverse.each do |comment| %>
			<p><%= comment.content%>
		Posted <%= time_ago_in_words(comment.created_at)%> ago by
		<%= comment.user.name %></p>
		<%end%>
		<h3>Star Rating</h3>
		<p>
			<%= number_with_precision(@movie.average_stars, precision: 0) %>
		</p>
	<%end%>
		

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>